name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
      branches: [main]

jobs:
  test:
    run-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        use: action/setup-node@v4

      - name: Intall Dependencies
        run: npm ci

      - name: Run Test
        run: npm test
